version: '3.7'

services:
  webhooks:
    build: .
    image: webhooks:latest
    container_name: webhooks
    restart: unless-stopped
    volumes:
      - /finkrer.wtf:/finkrer.wtf
    ports:
      - 8888:8888
